name: natural_gas_service
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API INTEGRATION
  dio: ^5.7.0                               # HTTP Client
  pretty_dio_logger: ^1.4.0                 # HTTP Client Logger
  flutter_client_sse: ^2.0.3                # Server Sent Event
  url_strategy: ^0.2.0                      # URL Strategy

  # DATA CONVERTERS
  easy_localization: ^3.0.7                 # Multi-Lang Support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
